VoyageAI reranking first version
voyage-ai/langchain pull request #10
Opened 2024-03-13 12:57 UTC by fzowl

Thank you for contributing to LangChain!

- [ ] **PR title**: "package: description"
  - Where "package" is whichever of langchain, community, core, experimental, etc. is being modified. Use "docs: ..." for purely docs changes, "templates: ..." for template changes, "infra: ..." for CI changes.
  - Example: "community: add foobar LLM"

- [ ] **PR message**: ***Delete this entire checklist*** and replace with
    - **Description:** a description of the change
    - **Issue:** the issue # it fixes, if applicable
    - **Dependencies:** any dependencies required for this change
    - **Twitter handle:** if your PR gets announced, and you'd like a mention, we'll gladly shout you out!

- [ ] **Add tests and docs**: If you're adding a new integration, please include
  1. a test for the integration, preferably unit tests that do not rely on network access,
  2. an example notebook showing its use. It lives in `docs/docs/integrations` directory.

- [ ] **Lint and test**: Run `make format`, `make lint` and `make test` from the root of the package(s) you've modified. See contribution guidelines for more: https://python.langchain.com/docs/contributing/

Additional guidelines:
- Make sure optional dependencies are imported within a function.
- Please do not add dependencies to pyproject.toml files (even optional ones) unless they are required for unit tests.
- Most PRs should not touch more than one package.
- Changes should be backwards compatible.
- If you are adding something to community, do not re-import it in langchain.

If no one reviews your PR within a few days, please @-mention one of baskaryan, efriis, eyurtsev, hwchase17.

2024-03-14 23:21 UTC, thomas0809 commented on libs/langchain/langchain/retrievers/document_compressors/voyageai_rerank.py
> +    top_k: Optional[int]
default to None

2024-03-14 23:34 UTC, thomas0809 commented on libs/langchain/langchain/retrievers/document_compressors/voyageai_rerank.py
> +        top_k: Optional[int] = -1,
I don't think we should introduce the default value of -1 here (although I saw they did this for cohere).
Let's do the following for `top_k` and `model`:

- still keep them as attributes to this class
- in this function, change the arguments to 
```py
def rerank(
    self,
    documents: Sequence[Union[str, Document]],
    query: str,
    **kwargs,
):
```
- and in the function
```py
top_k = kwargs.get("top_k", self.top_k)
model = kwargs.get("top_k", self.model)
```

2024-03-14 23:37 UTC, thomas0809 commented on libs/langchain/langchain/retrievers/document_compressors/voyageai_rerank.py
> +        top_k: Optional[int] = -1,
Same as the `rerank` function

2024-03-14 23:49 UTC, thomas0809 requested changes
Thanks for implementing the new class for our reranker.

LangChain probably won't want us to add code to the `libs/langchain` directory. We should move the code to https://github.com/langchain-ai/langchain/tree/master/libs/community/langchain_community/document_compressors at least.

Since we also have code in `libs/partners`, I am not sure whether it is best to add the code to `langchain_community` or `partners`. Let me ask the LangChain people about this.

2024-03-15 00:02 UTC, thomas0809 commented
> Thanks for implementing the new class for our reranker.
> 
> LangChain probably won't want us to add code to the `libs/langchain` directory. We should move the code to https://github.com/langchain-ai/langchain/tree/master/libs/community/langchain_community/document_compressors at least.
> 
> Since we also have code in `libs/partners`, I am not sure whether it is best to add the code to `langchain_community` or `partners`. Let me ask the LangChain people about this.

OK, they would like us to move the code to our package.

2024-03-19 18:15 UTC, thomas0809 commented on libs/langchain/pyproject.toml
> +voyageai = {version = "^0.2.1", optional = true}
They probably won't allow this. Since we are adding to our package, we don't have to add dependencies to the core langchain package?

2024-03-19 18:16 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +        model = kwargs.get("top_k", self.model)
model = kwargs.get("model", self.model)

2024-03-19 18:17 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +        model = kwargs.get("top_k", self.model)
Same

2024-03-19 18:19 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +        for res in results.results:
Why do you need to convert results to another format? I think you can return results directly. Is there any problem with this?

2024-03-19 18:42 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +        result_dicts = []
Same

2024-03-19 18:45 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +        for res in self.rerank(documents, query):
If we change the format of the returned object of self.rerank, it needs to be changed accordingly here

2024-03-19 18:45 UTC, thomas0809 requested changes
Please see my comments. Thanks!

2024-03-20 10:04 UTC, fzowl commented on libs/langchain/pyproject.toml
> +voyageai = {version = "^0.2.1", optional = true}
Yeah, that was precisely what i thought. But, as you can see there is a depency on the cohere and openai packages, that's why i thought we might add our package as well.
On the other hand, this might be due to historical reasons.

2024-03-20 10:15 UTC, fzowl commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +        for res in results.results:
Hm, you are right, since the names in our format and in the expected format are the same, it is possible.

2024-03-20 10:26 UTC, fzowl commented on libs/langchain/pyproject.toml
> +voyageai = {version = "^0.2.1", optional = true}
Anyway, i removed the same for now.

2024-03-20 18:53 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +        return self.aclient.rerank(
No await?

2024-03-20 18:53 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +        for res in self.rerank(documents, query):
I don't think this is supposed to work in this way.

2024-03-20 18:54 UTC, thomas0809 requested changes
See comments

2024-03-21 22:25 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +    top_k: Optional[int] = None
nit: Can we reorder these arguments? e.g. following the order in our docs, maybe voyageai_api_key first, then model, top_k, truncation

2024-03-21 22:26 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +            model: The model to use for re-ranking. Default to self.model.
this function doesn't have arguments model and top_k

2024-03-21 22:30 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/rerank.py
> +        for res in result.results:
nit: I think you could do `for res in (await self.arerank(documents, query)).results:` instead of using two lines?

This is merely trying to be consistent with the code in the above function.

2024-03-21 23:17 UTC, thomas0809 commented on libs/partners/voyageai/tests/unit_tests/test_rerank.py
> +    Usage = namedtuple("Usage", ["prompt_tokens", "total_tokens", "completion_tokens"])
Please remove "prompt_tokens" and "completion_tokens". We will be removing them.

2024-03-21 23:21 UTC, thomas0809 commented on libs/partners/voyageai/tests/unit_tests/test_rerank.py
> +    mock_result = RerankingObject(response=voyage_response, documents=["X", "Y"])
It is probably a bit confusing here. Maybe change it to `documents=doc_list`

2024-03-21 23:24 UTC, thomas0809 commented on docs/docs/integrations/retrievers/voyageai-reranker.ipynb
> +    "    texts, VoyageEmbeddings(model=\"voyage-02\")\n",
Please use `voyage-2` instead of `voyage-02`. In general, please never use `voyage-02` in anywhere in the future.

2024-03-21 23:25 UTC, thomas0809 requested changes
Some minor comments

2024-03-22 17:46 UTC, thomas0809 approved these changes

2024-03-23 18:21 UTC, merged