community: model attribute is required, set default batch size
voyage-ai/langchain pull request #3
Opened 2024-02-15 20:32 UTC by fzowl

- Change model to a required argument
 - Change the default batch size to 72 for model "voyage-2"/"voyage-02", and to 7 for all other models. (However, still allow the user to specify batch size)

2024-02-15 21:37 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
>      batch_size: int = 8
Please remove this line as it is no longer used.

2024-02-15 22:31 UTC, thomas0809 requested changes
Please see the additional comments. Thanks!

2024-02-15 22:31 UTC, thomas0809 commented on docs/docs/integrations/text_embedding/voyageai.ipynb
> +    "embeddings = VoyageEmbeddings(voyage_api_key=\"[ Your Voyage API key ]\", model=\"[model name]\")"
Let's just use `model="voyage-2"` here. Please also add a sentence that directs to our docs, like the user can find all the models there https://docs.voyageai.com/embeddings/

2024-02-16 18:58 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
> -    model: str = "voyage-01"
It shouldn't be deleting this line, right? I think it should be just `model: str`.
Can it pass the test if you delete this line? I am not sure, actually.

2024-02-16 18:59 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
>      batch_size: int = 8
This is not resolved yet.

2024-02-16 19:03 UTC, thomas0809 requested changes
Please see the comments

2024-02-16 21:05 UTC, fzowl commented on libs/community/langchain_community/embeddings/voyageai.py
> -    model: str = "voyage-01"
Yes, `model: str` is a must. Sorry, i blindly removed this line because of your previous comment to remove unused attributes. (also, i need to switch back to Python from JavaScript/TypeScript)

2024-02-16 21:09 UTC, fzowl commented on libs/community/langchain_community/embeddings/voyageai.py
>      batch_size: int = 8
Yes, makes sense. Made the change.

2024-02-16 21:54 UTC, thomas0809 approved these changes

2024-02-16 21:55 UTC, merged