Correcting due to the comments
voyage-ai/langchain pull request #5
Opened 2024-02-22 10:45 UTC by fzowl

(tests run successful)

2024-02-22 19:34 UTC, thomas0809 reviewed
Please address the comments as we discussed

2024-02-23 23:00 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
> +        if "model" not in values:
Have you tested if this warning will be raised? I am not 100% sure how this `@root_validator(pre=True)` works.

2024-02-23 23:01 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
> +        if "batch_size" not in values:
L139-140 should be deleted after moving this here. Also, L134 is no longer an optional argument.

2024-02-23 23:03 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
> +    model: str = "voyage-2"
Sorry that I might have made a wrong judgement before. We probably shouldn't change the default value here. Although we want to make it a required argument in the future, changing it is backward incompatible.
Therefore, please change it back to "voyage-01"

2024-02-23 23:04 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
> +                "Currently the default is set to voyage-2."
change the default accordingly

2024-02-23 23:11 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
> +                or (values["model"] in ["voyage-2", "voyage-02"])
After changing the default, this logic needs to be changed as well.

2024-02-23 23:20 UTC, thomas0809 commented on libs/community/tests/integration_tests/embeddings/test_voyageai.py
> +
Can we add a test to validate the batch_size is set as we expected, also the code can run for voyage-01 and voyage-2?
For example,
```python
embedding = VoyageEmbeddings()
assert embedding.model = "voyage-01"
assert embedding.batch_size = 7
documents  = [f"foo bar {I}" for i in range(72)]
output = embedding.embed_documents(documents)
assert len(output) == 72
assert len(output[0]) == 1024
```
and similarly for voyage-2

2024-02-23 23:20 UTC, thomas0809 requested changes
Changes required

2024-02-26 12:46 UTC, fzowl commented on libs/community/langchain_community/embeddings/voyageai.py
> +                or (values["model"] in ["voyage-2", "voyage-02"])
I hope this is what you meant

2024-02-27 00:16 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
> -        if batch_size is None:
After removing this two lines, this function will crash if batch_size is None.
Since we have checked batch_size in the validate_environment, self.batch_size now must be a valid int. Let's change this part back to the original, i.e.,
```python
if batch_size is None:
    batch_size = self.batch_size
```

2024-02-27 00:19 UTC, thomas0809 commented on libs/community/langchain_community/embeddings/voyageai.py
> +                "we recommend to specify it when using this class."
nit: add a space after "."?

2024-02-27 00:19 UTC, thomas0809 requested changes
Two small changes required.

2024-02-28 23:38 UTC, thomas0809 approved these changes

2024-02-28 23:40 UTC, merged