Voyageai package
voyage-ai/langchain pull request #6
Opened 2024-02-28 13:00 UTC by fzowl

2024-02-29 19:16 UTC, thomas0809 commented on libs/community/pyproject.toml
> -select = [
I don't think they will allow changes in this file (as they don't seem to be necessary)

2024-02-29 19:17 UTC, thomas0809 commented on libs/partners/voyageai/.gitignore
> +__pycache__
Delete this file. Instead of creating a .gitignore file, there are alternatives https://stackoverflow.com/questions/1753070/how-do-i-configure-git-to-ignore-some-files-locally

2024-02-29 19:18 UTC, thomas0809 commented on libs/partners/voyageai/LICENSE
> +Copyright (c) 2023 LangChain, Inc.
Change to "Copyright (c) 2023 Voyage AI"

2024-02-29 19:23 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/embeddings.py
> +        embed_batch_size: Optional[int] = None,
add "truncation"

2024-02-29 19:24 UTC, thomas0809 requested changes
Please see my comments.

2024-03-03 23:02 UTC, fzowl commented on libs/partners/voyageai/.gitignore
> +__pycache__
This file was generated by langchain CLI

2024-03-04 10:12 UTC, fzowl commented
@thomas0809 Can you please help with the documentation (docs folder) and the README?

2024-03-06 18:10 UTC, thomas0809 reviewed
One small edit

2024-03-06 18:10 UTC, thomas0809 commented on libs/partners/voyageai/langchain_voyageai/embeddings.py
> +    model: str = "voyage-01"
remove the default values

2024-03-06 22:08 UTC, thomas0809 approved these changes

2024-03-06 22:08 UTC, merged